/**
 * @fileoverview UI label dictionary — Spanish native.
 *
 * The app is Spanish-only by decision (2026-07-05, demo-readiness plan §4.3):
 * the former i18next stack translated exactly one component and shipped a
 * language toggle that did nothing, so it was removed. This module keeps the
 * useLanguage().t('flatKey') API that ~18 components already use, backed by a
 * plain dictionary instead of a translation runtime.
 *
 * Adding a label: add the key here and call t('myKey'). Unknown keys return
 * the key itself so a typo is visible in the UI rather than a crash.
 */

const LABELS: Record<string, string> = {
  login: "Iniciar Sesión",
  email: "Correo Electrónico",
  password: "Contraseña",
  logout: "Cerrar Sesión",
  supervisorDashboard: "Panel del Supervisor",
  managerDashboard: "Panel del Gerente",
  adminDashboard: "Panel de Administración",
  totalUsers: "Total de Usuarios",
  totalWorkers: "Total de Trabajadores",
  totalJobs: "Total de Trabajos",
  machines: "Máquinas",
  jobs: "Trabajos",
  reports: "Reportes",
  users: "Usuarios",
  workers: "Trabajadores",
  inventory: "Inventario",
  purchases: "Compras",
  userManagement: "Gestión de Usuarios",
  addUser: "Agregar Usuario",
  editUser: "Editar Usuario",
  role: "Rol",
  department: "Departamento",
  managerDomain: "Dominio del Gerente",
  addUserDescription: "Crear un nuevo usuario con rol y departamento",
  editUserDescription: "Modificar rol y departamento del usuario",
  workersManagement: "Gestión de Trabajadores",
  addWorker: "Agregar Trabajador",
  editWorker: "Editar Trabajador",
  addWorkerDescription: "Agregar un nuevo trabajador al sistema",
  editWorkerDescription: "Modificar información del trabajador",
  workerRoster: "Planilla de Trabajadores",
  createRoster: "Crear Planilla",
  rosterName: "Nombre de Planilla",
  addToRoster: "Agregar a Planilla",
  removeFromRoster: "Quitar de Planilla",
  allWorkers: "Todos los Trabajadores",
  filterByDept: "Filtrar por Departamento",
  sortBy: "Ordenar por",
  workerStats: "Estadísticas de Trabajadores",
  viewStats: "Ver Estadísticas",
  performance: "Rendimiento",
  avgTime: "Tiempo Promedio",
  rating: "Calificación",
  efficiencyScore: "Eficiencia",
  totalTasks: "Total de Tareas",
  logTask: "Registrar Tarea",
  taskType: "Tipo de Tarea",
  timeSpent: "Tiempo Dedicado (min)",
  notes: "Notas",
  inventoryManagement: "Gestión de Inventario",
  addItem: "Agregar Artículo",
  editItem: "Editar Artículo",
  itemName: "Nombre del Artículo",
  quantity: "Cantidad",
  costPerUnit: "Costo por Unidad",
  supplier: "Proveedor",
  totalCost: "Costo Total",
  certificationDetails: "Detalles de Certificación",
  addItemDescription: "Agregar un artículo al inventario",
  editItemDescription: "Modificar información del artículo",
  purchasesManagement: "Gestión de Compras",
  addPurchase: "Agregar Compra",
  editPurchase: "Editar Compra",
  addPurchaseDescription: "Registrar una nueva compra",
  editPurchaseDescription: "Modificar detalles de la compra",
  admin: "Administrador",
  manager: "Gerente",
  supervisor: "Supervisor",
  press: "Prensa",
  deliveries: "Entregas",
  administration: "Administración",
  pre_press: "Pre-Prensa",
  manual_workshop: "Taller Manual",
  cost: "Costos",
  production: "Producción",
  quality: "Calidad",
  idle: "Inactiva",
  running: "En Marcha",
  maintenance: "En Mantenimiento",
  offline: "Fuera de Línea",
  setup: "En Preparación",
  breakdown: "Avería",
  pending: "Pendiente",
  in_progress: "En Progreso",
  completed: "Completado",
  delivered: "Entregado",
  offset_printer: "Impresora Offset",
  die_cutter: "Troqueladora",
  guillotine: "Guillotina",
  digital_printer: "Impresora Digital",
  addJob: "Agregar Trabajo",
  updateStatus: "Actualizar Estado",
  addOT: "Agregar OT",
  addBatch: "Agregar Lote",
  viewTraceability: "Ver Trazabilidad",
  exportPDF: "Exportar PDF",
  assignWorker: "Asignar Trabajador",
  assignBatch: "Asignar Lote",
  ot: "Órdenes de Trabajo (OT)",
  otNumber: "Número de OT",
  otList: "Órdenes de Trabajo",
  createOT: "Crear Orden de Trabajo",
  batch: "Lote",
  batches: "Lotes",
  batchNumber: "Número de Lote",
  paperType: "Tipo de Papel",
  quantityRemaining: "Cantidad Restante",
  certifications: "Certificaciones",
  totalJobCost: "Costo Total del Trabajo",
  materialCost: "Costo de Materiales",
  laborCost: "Costo de Mano de Obra",
  machineCost: "Costo de Máquinas",
  costBreakdown: "Desglose de Costos",
  costReport: "Reporte de Costos",
  efficiencyReport: "Reporte de Eficiencia",
  traceabilityReport: "Reporte de Trazabilidad",
  completedJobs: "Trabajos Completados",
  pendingJobs: "Trabajos Pendientes",
  efficiency: "Eficiencia",
  totalOTs: "Total de OTs",
  jobsPerDay: "Trabajos por Día",
  processFlow: "Flujo de Proceso",
  timeline: "Línea de Tiempo",
  detachment: "Desprendimiento",
  revision: "Revisión",
  packaging: "Empaque",
  printing: "Impresión",
  cutting: "Corte",
  name: "Nombre",
  actions: "Acciones",
  date: "Fecha",
  description: "Descripción",
  status: "Estado",
  submit: "Enviar",
  cancel: "Cancelar",
  save: "Guardar",
  edit: "Editar",
  delete: "Eliminar",
  view: "Ver",
  overview: "Resumen",
  noData: "No hay datos disponibles",
  search: "Buscar",
  createdAt: "Creado el",
  confirmDelete: "¿Estás seguro de que quieres eliminar esto?",
  create: "Crear",
  update: "Actualizar",
  machine: "Máquinas",
  worker: "Trabajadores",
  delivery: "Entregas",
};

function t(key: string): string {
  return LABELS[key] ?? key;
}

/** Kept name/shape so existing `const { t } = useLanguage()` call sites work unchanged. */
export function useLanguage(): { t: (key: string) => string } {
  return { t };
}
