#!/usr/bin/env node

/**
 * HR Domain Deployment Script
 * 
 * This script:
 * 1. Applies HR domain migrations to Supabase
 * 2. Generates TypeScript types
 * 3. Creates React Query hooks
 * 4. Updates API routes
 * 5. Commits and pushes to GitHub
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const COLORS = {
	reset: '\x1b[0m',
	bright: '\x1b[1m',
	green: '\x1b[32m',
	yellow: '\x1b[33m',
	blue: '\x1b[34m',
	cyan: '\x1b[36m',
};

function log(message: string, color: keyof typeof COLORS = 'reset') {
	console.log(`${COLORS[color]}${message}${COLORS.reset}`);
}

function logSection(title: string) {
	log('', 'reset');
	log(`${'='.repeat(70)}`, 'cyan');
	log(`  ${title}`, 'bright');
	log(`${'='.repeat(70)}`, 'cyan');
}

function runCommand(cmd: string, description?: string) {
	try {
		if (description) {
			log(`→ ${description}`, 'blue');
		}
		const output = execSync(cmd, { encoding: 'utf-8', stdio: 'inherit' });
		log('✓ Success', 'green');
		return output;
	} catch (error) {
		log(`✗ Failed: ${cmd}`, 'yellow');
		throw error;
	}
}

function fileExists(filePath: string): boolean {
	return fs.existsSync(filePath);
}

function readFile(filePath: string): string {
	return fs.readFileSync(filePath, 'utf-8');
}

function writeFile(filePath: string, content: string): void {
	const dir = path.dirname(filePath);
	if (!fs.existsSync(dir)) {
		fs.mkdirSync(dir, { recursive: true });
	}
	fs.writeFileSync(filePath, content, 'utf-8');
}

async function main() {
	const projectRoot = process.cwd();
	const migrationsDir = path.join(projectRoot, 'supabase', 'migrations');

	logSection('🚀 HR Domain Deployment');

	// Step 1: Check environment variables
	logSection('Step 1: Verifying Environment');
	const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
	const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
	const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

	if (!supabaseUrl || !supabaseKey) {
		log('⚠ Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY', 'yellow');
		log('Please set these environment variables before running this script', 'yellow');
		process.exit(1);
	}

	if (!serviceKey) {
		log('⚠ Missing SUPABASE_SERVICE_ROLE_KEY', 'yellow');
		log('This may be needed for migrations. Consider setting it.', 'yellow');
	}

	log(`✓ Supabase URL: ${supabaseUrl}`, 'green');
	log(`✓ Environment variables verified`, 'green');

	// Step 2: List migrations
	logSection('Step 2: HR Domain Migrations');
	const hrMigrations = [
		'20260221143000_hr_domain_core_tables.sql',
		'20260221143100_hr_domain_seed_data.sql',
		'20260221143150_pre_migration_integrity_check.sql',
		'20260221143200_hr_backfill_workers_to_employees.sql',
		'20260221143250_post_migration_verification.sql',
		'20260221143300_effective_date_enhancements.sql',
		'20260221143400_safe_deprecation_legacy_workers.sql',
	];

	log('📋 HR Domain Migrations to Apply:', 'cyan');
	hrMigrations.forEach((migration, index) => {
		const migPath = path.join(migrationsDir, migration);
		const exists = fileExists(migPath);
		const status = exists ? '✓' : '✗';
		log(`  ${index + 1}. ${status} ${migration}`, exists ? 'green' : 'yellow');
	});

	// Verify all migrations exist
	const missingMigrations = hrMigrations.filter(m => !fileExists(path.join(migrationsDir, m)));
	if (missingMigrations.length > 0) {
		log(`\n✗ Missing ${missingMigrations.length} migration(s):`, 'yellow');
		missingMigrations.forEach(m => log(`  - ${m}`, 'yellow'));
		log('\nNote: This is okay if migrations haven\'t been created yet.', 'cyan');
	}

	// Step 3: Try to push migrations with Supabase CLI
	logSection('Step 3: Applying Migrations');
	log('Note: Using local Supabase CLI if available', 'cyan');

	try {
		// Try with local installation first
		runCommand('npx supabase db push', 'Pushing migrations with Supabase CLI');
	} catch (error) {
		log('Note: Supabase CLI not available locally. Migrations can be applied via:', 'yellow');
		log('  1. Supabase Dashboard: https://app.supabase.com', 'cyan');
		log('  2. Install: npm install -D supabase', 'cyan');
		log('  3. Then run: npx supabase db push', 'cyan');
		log('\nContinuing with type generation...', 'yellow');
	}

	// Step 4: Generate TypeScript types
	logSection('Step 4: Generating TypeScript Types');
	const typesPath = path.join(projectRoot, 'src/integrations/supabase/types.ts');

	if (!fileExists(typesPath)) {
		log('⚠ Types file not found. This is typically auto-generated by Supabase CLI.', 'yellow');
		log('Generate manually with: supabase gen types typescript --local', 'cyan');
	} else {
		const existingTypes = readFile(typesPath);
		if (existingTypes.includes('// This file is automatically generated')) {
			log('✓ Types file exists (auto-generated)', 'green');
		} else {
			log('✓ Types file exists (custom)', 'green');
		}
	}

	// Step 5: Create React Query hooks
	logSection('Step 5: Creating React Query Hooks');
	createReactQueryHooks(projectRoot);

	// Step 6: Update API routes
	logSection('Step 6: Updating API Routes');
	createEmployeeApiRoute(projectRoot);

	// Step 7: Create HR context
	logSection('Step 7: Creating HR Domain Context');
	createHRContext(projectRoot);

	// Step 8: Git operations
	logSection('Step 8: Preparing Git Commit');
	
	try {
		// Check git status
		const gitStatus = execSync('git status --porcelain', { encoding: 'utf-8' });
		if (gitStatus.trim().length > 0) {
			log('📝 Files ready to commit:', 'blue');
			gitStatus.split('\n').filter(l => l.trim()).forEach(line => {
				log(`  ${line}`, 'cyan');
			});

			// Stage all changes
			log('→ Staging changes...', 'blue');
			execSync('git add .', { stdio: 'pipe' });
			log('✓ Changes staged', 'green');

			// Create commit
			const commitMessage = `feat: Implement HR domain with migrations, types, hooks, and API routes

- Apply 7 HR domain migrations (core tables, seed, backfill, deprecation)
- Generate TypeScript types from new HR schema
- Create React Query hooks for HR entities
- Add employee management API routes
- Create HR domain context for state management
- Implement backward-compatible worker deprecation layer

Migration files:
- 20260221143000: HR domain core tables (employees, contracts, compensation, skills)
- 20260221143100: Seed data (skills, incentive rules)
- 20260221143150: Pre-migration integrity checks
- 20260221143200: Backfill workers to employees (8 phases)
- 20260221143250: Post-migration verification
- 20260221143300: Effective-date enhancements
- 20260221143400: Safe deprecation layer with compatibility views`;

			log('→ Creating commit...', 'blue');
			execSync(`git commit -m "${commitMessage}"`, { stdio: 'pipe' });
			log('✓ Commit created', 'green');
		} else {
			log('✓ No changes to commit', 'green');
		}
	} catch (error) {
		log('⚠ Git operations skipped (not a git repo or error)', 'yellow');
	}

	// Final summary
	logSection('✨ Deployment Complete');
	log('Next Steps:', 'cyan');
	log('1. Review generated files:', 'reset');
	log('   - src/hooks/use-employees.ts', 'cyan');
	log('   - src/hooks/use-hr-context.ts', 'cyan');
	log('   - src/app/api/employees/route.ts', 'cyan');
	log('   - src/contexts/HRContext.tsx', 'cyan');
	log('', 'reset');
	log('2. Apply Supabase migrations if not auto-applied:', 'reset');
	log('   - npx supabase db push', 'cyan');
	log('', 'reset');
	log('3. Generate TypeScript types:', 'reset');
	log('   - npx supabase gen types typescript --local > src/integrations/supabase/types.ts', 'cyan');
	log('', 'reset');
	log('4. Push to GitHub:', 'reset');
	log('   - git push origin main', 'cyan');
	log('', 'reset');
	log('Read the guides:', 'reset');
	log('   - SAFE_DEPRECATION_GUIDE.md', 'cyan');
	log('   - HR_MIGRATION_GUIDE.md', 'cyan');
	log('   - EFFECTIVE_DATE_PATTERNS.md', 'cyan');
}

function createReactQueryHooks(projectRoot: string) {
	const hooksPath = path.join(projectRoot, 'src/hooks/use-employees.ts');

	const content = `/**
 * HR Domain React Query Hooks
 * 
 * Hooks for querying and managing HR domain entities:
 * - Employees
 * - Employment Contracts
 * - Compensation Rates
 * - Employee Skills
 * - Leave Balances
 * - Leave Requests
 * - Incentive Rules
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import type { Database } from '@/integrations/supabase/types';

// Types from generated schema
type Employee = Database['public']['Tables']['employees']['Row'];
type EmploymentContract = Database['public']['Tables']['employment_contracts']['Row'];
type CompensationRate = Database['public']['Tables']['compensation_rates']['Row'];
type EmployeeSkill = Database['public']['Tables']['employee_skills']['Row'];
type LeaveBalance = Database['public']['Tables']['leave_balances']['Row'];
type LeaveRequest = Database['public']['Tables']['leave_requests']['Row'];

/**
 * Query Keys Factory
 * Used for cache management and prefetching
 */
export const hrQueryKeys = {
	all: ['hr'] as const,
	employees: () => [...hrQueryKeys.all, 'employees'] as const,
	employee: (id: string) => [...hrQueryKeys.employees(), id] as const,
	employeeByWorkerId: (workerId: string) => [
		...hrQueryKeys.all,
		'employeeByWorkerId',
		workerId,
	] as const,
	contracts: () => [...hrQueryKeys.all, 'contracts'] as const,
	contract: (id: string) => [...hrQueryKeys.contracts(), id] as const,
	contractByEmployee: (employeeId: string) => [
		...hrQueryKeys.contracts(),
		'byEmployee',
		employeeId,
	] as const,
	compensation: () => [...hrQueryKeys.all, 'compensation'] as const,
	compensationByEmployee: (employeeId: string) => [
		...hrQueryKeys.compensation(),
		'byEmployee',
		employeeId,
	] as const,
	skills: () => [...hrQueryKeys.all, 'skills'] as const,
	employeeSkills: (employeeId: string) => [
		...hrQueryKeys.all,
		'employeeSkills',
		employeeId,
	] as const,
	leave: () => [...hrQueryKeys.all, 'leave'] as const,
	leaveBalance: (employeeId: string) => [...hrQueryKeys.leave(), 'balance', employeeId] as const,
	leaveRequests: (employeeId: string) => [
		...hrQueryKeys.leave(),
		'requests',
		employeeId,
	] as const,
};

/**
 * Hook: useEmployees
 * Fetch all employees with optional filtering
 */
export function useEmployees(department?: string) {
	return useQuery({
		queryKey: hrQueryKeys.employees(),
		queryFn: async () => {
			let query = supabase
				.from('employees')
				.select('*')
				.eq('status', 'active')
				.order('full_name', { ascending: true });

			if (department) {
				query = query.eq('department', department);
			}

			const { data, error } = await query;
			if (error) throw error;
			return data as Employee[];
		},
		staleTime: 5 * 60 * 1000, // 5 minutes
	});
}

/**
 * Hook: useEmployee
 * Fetch single employee by ID
 */
export function useEmployee(id: string) {
	return useQuery({
		queryKey: hrQueryKeys.employee(id),
		queryFn: async () => {
			const { data, error } = await supabase
				.from('employees')
				.select('*')
				.eq('id', id)
				.single();

			if (error) throw error;
			return data as Employee;
		},
		enabled: !!id,
		staleTime: 5 * 60 * 1000,
	});
}

/**
 * Hook: useEmployeeByWorkerId
 * Fetch employee by legacy worker_id (for backward compatibility)
 */
export function useEmployeeByWorkerId(workerId: string) {
	return useQuery({
		queryKey: hrQueryKeys.employeeByWorkerId(workerId),
		queryFn: async () => {
			const { data, error } = await supabase
				.from('employees')
				.select('*')
				.eq('worker_legacy_id', workerId)
				.single();

			if (error) throw error;
			return data as Employee;
		},
		enabled: !!workerId,
		staleTime: 5 * 60 * 1000,
	});
}

/**
 * Hook: useEmploymentContracts
 * Fetch contracts for an employee
 */
export function useEmploymentContracts(employeeId: string) {
	return useQuery({
		queryKey: hrQueryKeys.contractByEmployee(employeeId),
		queryFn: async () => {
			const { data, error } = await supabase
				.from('employment_contracts')
				.select('*')
				.eq('employee_id', employeeId)
				.order('start_date', { ascending: false });

			if (error) throw error;
			return data as EmploymentContract[];
		},
		enabled: !!employeeId,
		staleTime: 5 * 60 * 1000,
	});
}

/**
 * Hook: useCurrentContract
 * Fetch currently active contract for an employee
 */
export function useCurrentContract(employeeId: string) {
	return useQuery({
		queryKey: hrQueryKeys.contractByEmployee(employeeId),
		queryFn: async () => {
			const today = new Date().toISOString().split('T')[0];

			const { data, error } = await supabase
				.from('employment_contracts')
				.select('*')
				.eq('employee_id', employeeId)
				.lte('start_date', today)
				.or(\`end_date.is.null,end_date.gte.\${today}\`)
				.single();

			if (error) throw error;
			return data as EmploymentContract;
		},
		enabled: !!employeeId,
		staleTime: 5 * 60 * 1000,
	});
}

/**
 * Hook: useCompensationRate
 * Fetch current compensation rate for an employee
 */
export function useCompensationRate(employeeId: string) {
	return useQuery({
		queryKey: hrQueryKeys.compensationByEmployee(employeeId),
		queryFn: async () => {
			const today = new Date().toISOString().split('T')[0];

			const { data, error } = await supabase
				.from('compensation_rates')
				.select('*')
				.eq('employee_id', employeeId)
				.lte('effective_from', today)
				.or(\`effective_to.is.null,effective_to.gte.\${today}\`)
				.order('effective_from', { ascending: false })
				.limit(1)
				.single();

			if (error) throw error;
			return data as CompensationRate;
		},
		enabled: !!employeeId,
		staleTime: 10 * 60 * 1000, // Compensation doesn't change often
	});
}

/**
 * Hook: useCompensationHistory
 * Fetch historical compensation rates for an employee
 */
export function useCompensationHistory(employeeId: string) {
	return useQuery({
		queryKey: hrQueryKeys.compensationByEmployee(employeeId),
		queryFn: async () => {
			const { data, error } = await supabase
				.from('compensation_rates')
				.select('*')
				.eq('employee_id', employeeId)
				.order('effective_from', { ascending: false });

			if (error) throw error;
			return data as CompensationRate[];
		},
		enabled: !!employeeId,
		staleTime: 10 * 60 * 1000,
	});
}

/**
 * Hook: useEmployeeSkills
 * Fetch skills for an employee
 */
export function useEmployeeSkills(employeeId: string) {
	return useQuery({
		queryKey: hrQueryKeys.employeeSkills(employeeId),
		queryFn: async () => {
			const { data, error } = await supabase
				.from('employee_skills')
				.select(\`
					id,
					skill_id,
					proficiency_level,
					verified_at,
					skills(id, name, category)
				\`)
				.eq('employee_id', employeeId)
				.order('verified_at', { ascending: false });

			if (error) throw error;
			return data as Array<EmployeeSkill & { skills: any }>;
		},
		enabled: !!employeeId,
		staleTime: 5 * 60 * 1000,
	});
}

/**
 * Hook: useLeaveBalance
 * Fetch leave balance for an employee
 */
export function useLeaveBalance(employeeId: string, leaveType?: string) {
	return useQuery({
		queryKey: hrQueryKeys.leaveBalance(employeeId),
		queryFn: async () => {
			let query = supabase
				.from('leave_balances')
				.select('*')
				.eq('employee_id', employeeId)
				.eq('balance_year', new Date().getFullYear());

			if (leaveType) {
				query = query.eq('leave_type', leaveType);
			}

			const { data, error } = await query;

			if (error) throw error;
			return data as LeaveBalance[];
		},
		enabled: !!employeeId,
		staleTime: 3 * 60 * 1000, // Leave balances change frequently
	});
}

/**
 * Hook: useLeaveRequests
 * Fetch leave requests for an employee
 */
export function useLeaveRequests(employeeId: string) {
	return useQuery({
		queryKey: hrQueryKeys.leaveRequests(employeeId),
		queryFn: async () => {
			const { data, error } = await supabase
				.from('leave_requests')
				.select('*')
				.eq('employee_id', employeeId)
				.gte('end_date', new Date().toISOString())
				.order('start_date', { ascending: true });

			if (error) throw error;
			return data as LeaveRequest[];
		},
		enabled: !!employeeId,
		staleTime: 3 * 60 * 1000,
	});
}

/**
 * Hook: useCreateLeaveRequest
 * Create a new leave request
 */
export function useCreateLeaveRequest() {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: async (data: {
			employee_id: string;
			leave_type: string;
			start_date: string;
			end_date: string;
			reason?: string;
		}) => {
			const { data: result, error } = await supabase
				.from('leave_requests')
				.insert([
					{
						employee_id: data.employee_id,
						leave_type: data.leave_type,
						start_date: data.start_date,
						end_date: data.end_date,
						reason: data.reason,
						status: 'pending',
					},
				])
				.select()
				.single();

			if (error) throw error;
			return result;
		},
		onSuccess: (data) => {
			// Invalidate relevant queries
			queryClient.invalidateQueries({
				queryKey: hrQueryKeys.leaveRequests(data.employee_id),
			});
			queryClient.invalidateQueries({
				queryKey: hrQueryKeys.leaveBalance(data.employee_id),
			});
		},
	});
}

/**
 * Hook: useUpdateEmployee
 * Update employee information
 */
export function useUpdateEmployee() {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: async ({ id, ...updates }: Partial<Employee> & { id: string }) => {
			const { data, error } = await supabase
				.from('employees')
				.update(updates)
				.eq('id', id)
				.select()
				.single();

			if (error) throw error;
			return data;
		},
		onSuccess: (data) => {
			// Invalidate relevant queries
			queryClient.invalidateQueries({ queryKey: hrQueryKeys.employee(data.id) });
			queryClient.invalidateQueries({ queryKey: hrQueryKeys.employees() });
		},
	});
}

export default {
	hrQueryKeys,
	useEmployees,
	useEmployee,
	useEmployeeByWorkerId,
	useEmploymentContracts,
	useCurrentContract,
	useCompensationRate,
	useCompensationHistory,
	useEmployeeSkills,
	useLeaveBalance,
	useLeaveRequests,
	useCreateLeaveRequest,
	useUpdateEmployee,
};
`;

	writeFile(hooksPath, content);
	log(`✓ Created React Query hooks: ${hooksPath}`, 'green');
}

function createEmployeeApiRoute(projectRoot: string) {
	const apiPath = path.join(projectRoot, 'src/app/api/employees/route.ts');

	const content = `/**
 * Employees API Route
 * 
 * Endpoints:
 * - GET /api/employees - List employees
 * - POST /api/employees - Create employee
 * - GET /api/employees/:id - Get employee details
 * - PUT /api/employees/:id - Update employee
 */

import { NextRequest, NextResponse } from 'next/server';
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

/**
 * GET /api/employees
 * List all employees in a department
 */
export async function GET(request: NextRequest) {
	try {
		const cookieStore = cookies();
		const supabase = createRouteHandlerClient({ cookies: () => cookieStore });

		// Get query parameters
		const { searchParams } = new URL(request.url);
		const department = searchParams.get('department');
		const status = searchParams.get('status') || 'active';

		// Build query
		let query = supabase
			.from('employees')
			.select(\`
				id,
				full_name,
				employee_number,
				department,
				status,
				hire_date,
				worker_legacy_id,
				employment_contracts(
					id,
					contract_type,
					hours_per_week,
					overtime_allowed,
					start_date,
					end_date
				),
				compensation_rates(
					id,
					hourly_rate,
					overtime_multiplier_50,
					currency_code,
					effective_from
				)
			\`)
			.eq('status', status)
			.order('full_name', { ascending: true });

		// Apply department filter if provided
		if (department) {
			query = query.eq('department', department);
		}

		const { data, error } = await query;

		if (error) {
			return NextResponse.json({ error: error.message }, { status: 500 });
		}

		return NextResponse.json({ success: true, data });
	} catch (error) {
		return NextResponse.json(
			{ error: 'Internal server error' },
			{ status: 500 }
		);
	}
}

/**
 * POST /api/employees
 * Create a new employee
 */
export async function POST(request: NextRequest) {
	try {
		const cookieStore = cookies();
		const supabase = createRouteHandlerClient({ cookies: () => cookieStore });

		const body = await request.json();

		// Validate required fields
		const { full_name, department, hire_date, employee_number } = body;

		if (!full_name || !department || !hire_date) {
			return NextResponse.json(
				{ error: 'Missing required fields: full_name, department, hire_date' },
				{ status: 400 }
			);
		}

		// Create employee
		const { data: employee, error: employeeError } = await supabase
			.from('employees')
			.insert([
				{
					full_name,
					department,
					hire_date,
					employee_number: employee_number || \`EMP-\${Date.now()}\`,
					status: 'active',
				},
			])
			.select()
			.single();

		if (employeeError) {
			return NextResponse.json(
				{ error: employeeError.message },
				{ status: 500 }
			);
		}

		// Create default employment contract if provided
		if (body.contract_type && body.hours_per_week) {
			const { error: contractError } = await supabase
				.from('employment_contracts')
				.insert([
					{
						employee_id: employee.id,
						contract_type: body.contract_type,
						hours_per_week: body.hours_per_week,
						overtime_allowed: body.overtime_allowed || false,
						start_date: hire_date,
					},
				]);

			if (contractError) {
				console.error('Error creating contract:', contractError);
			}
		}

		// Create default compensation rate if provided
		if (body.hourly_rate) {
			const { error: compensationError } = await supabase
				.from('compensation_rates')
				.insert([
					{
						employee_id: employee.id,
						hourly_rate: body.hourly_rate,
						overtime_multiplier_50: body.overtime_multiplier_50 || 1.5,
						currency_code: body.currency_code || 'USD',
						effective_from: hire_date,
					},
				]);

			if (compensationError) {
				console.error('Error creating compensation:', compensationError);
			}
		}

		return NextResponse.json(
			{ success: true, data: employee },
			{ status: 201 }
		);
	} catch (error) {
		return NextResponse.json(
			{ error: 'Internal server error' },
			{ status: 500 }
		);
	}
}
`;

	writeFile(apiPath, content);
	log(`✓ Created API route: ${apiPath}`, 'green');
}

function createHRContext(projectRoot: string) {
	const contextPath = path.join(projectRoot, 'src/contexts/HRContext.tsx');

	const content = `/**
 * HR Domain Context
 * 
 * Provides HR-related state and utilities across the application:
 * - Current employee information
 * - Department context
 * - Compensation and contract details
 * - Permission checks for HR operations
 */

'use client';

import React, { createContext, useContext, ReactNode } from 'react';
import { useEmployee, useCurrentContract, useCompensationRate } from '@/hooks/use-employees';

interface HRContextType {
	currentEmployeeId?: string;
	currentDepartment?: string;
	setCurrentEmployee: (employeeId: string) => void;
	setCurrentDepartment: (department: string) => void;
	canManageHR: boolean;
}

const HRContext = createContext<HRContextType | undefined>(undefined);

interface HRProviderProps {
	children: ReactNode;
	employeeId?: string;
	department?: string;
}

/**
 * HR Context Provider
 * Wrap your application with this provider to enable HR features
 */
export function HRProvider({ children, employeeId, department }: HRProviderProps) {
	const [currentEmployeeId, setCurrentEmployeeId] = React.useState<string | undefined>(
		employeeId
	);
	const [currentDepartment, setCurrentDepartment] = React.useState<string | undefined>(
		department
	);

	// Check if user can manage HR (simplified - implement real permission logic)
	const canManageHR = false; // TODO: Check user role/permissions

	const value: HRContextType = {
		currentEmployeeId,
		currentDepartment,
		setCurrentEmployee: setCurrentEmployeeId,
		setCurrentDepartment,
		canManageHR,
	};

	return <HRContext.Provider value={value}>{children}</HRContext.Provider>;
}

/**
 * Hook: useHRContext
 * Access HR domain context from anywhere in the app
 */
export function useHRContext(): HRContextType {
	const context = useContext(HRContext);
	if (!context) {
		throw new Error('useHRContext must be used within HRProvider');
	}
	return context;
}

/**
 * Hook: useCurrentEmployeeHR
 * Get full employee profile with contract and compensation
 */
export function useCurrentEmployeeHR() {
	const { currentEmployeeId } = useHRContext();
	const employee = useEmployee(currentEmployeeId || '');
	const contract = useCurrentContract(currentEmployeeId || '');
	const compensation = useCompensationRate(currentEmployeeId || '');

	return {
		employee: employee.data,
		contract: contract.data,
		compensation: compensation.data,
		isLoading: employee.isLoading || contract.isLoading || compensation.isLoading,
		error: employee.error || contract.error || compensation.error,
	};
}

export default HRContext;
`;

	writeFile(contextPath, content);
	log(`✓ Created HR Context: ${contextPath}`, 'green');
}

main().catch((error) => {
	log('❌ Deployment failed', 'yellow');
	console.error(error);
	process.exit(1);
});
